// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  roomId: __t.u64().name("room_id"),
  x: __t.f64(),
  y: __t.f64(),
  dirX: __t.f64().name("dir_x"),
  dirY: __t.f64().name("dir_y"),
  speedBoostUntilMicros: __t.u64().name("speed_boost_until_micros"),
  abilityCooldownUntilMicros: __t.u64().name("ability_cooldown_until_micros"),
  health: __t.u32(),
  maxHealth: __t.u32().name("max_health"),
});
