// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  roundActive: __t.bool().name("round_active"),
  roundNumber: __t.u64().name("round_number"),
  roundStartMicros: __t.u64().name("round_start_micros"),
  roundEndMicros: __t.u64().name("round_end_micros"),
  lastTickMicros: __t.u64().name("last_tick_micros"),
  mapWidth: __t.f64().name("map_width"),
  mapHeight: __t.f64().name("map_height"),
  roundWinner: __t.option(__t.string()).name("round_winner"),
});
