// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const BotZombie = __t.object("BotZombie", {
  id: __t.u64(),
  roomId: __t.u64(),
  x: __t.f64(),
  y: __t.f64(),
  dirX: __t.f64(),
  dirY: __t.f64(),
  speedBoostUntilMicros: __t.u64(),
  abilityCooldownUntilMicros: __t.u64(),
});
export type BotZombie = __Infer<typeof BotZombie>;

export const GameConfig = __t.object("GameConfig", {
  id: __t.u64(),
  roundActive: __t.bool(),
  roundNumber: __t.u64(),
  roundStartMicros: __t.u64(),
  roundEndMicros: __t.u64(),
  lastTickMicros: __t.u64(),
  lastBotZombieSpawnMicros: __t.u64(),
  mapWidth: __t.f64(),
  mapHeight: __t.f64(),
  roundWinner: __t.option(__t.string()),
  gameMode: __t.option(__t.string()),
});
export type GameConfig = __Infer<typeof GameConfig>;

export const Obstacle = __t.object("Obstacle", {
  id: __t.u64(),
  roomId: __t.u64(),
  groupId: __t.u64(),
  x: __t.f64(),
  y: __t.f64(),
  width: __t.f64(),
  height: __t.f64(),
  obstacleType: __t.string(),
});
export type Obstacle = __Infer<typeof Obstacle>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  roomId: __t.u64(),
  x: __t.f64(),
  y: __t.f64(),
  dirX: __t.f64(),
  dirY: __t.f64(),
  isZombie: __t.bool(),
  isBot: __t.bool(),
  name: __t.string(),
  score: __t.u64(),
  speedBoostUntilMicros: __t.u64(),
  abilityCooldownUntilMicros: __t.u64(),
});
export type Player = __Infer<typeof Player>;

