// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import FireWeaponReducer from "../fire_weapon_reducer";
import JoinRoomReducer from "../join_room_reducer";
import LeaveRoomReducer from "../leave_room_reducer";
import SetInputReducer from "../set_input_reducer";
import SetNameReducer from "../set_name_reducer";
import TickReducer from "../tick_reducer";
import UseZombieAbilityReducer from "../use_zombie_ability_reducer";

export type FireWeaponParams = __Infer<typeof FireWeaponReducer>;
export type JoinRoomParams = __Infer<typeof JoinRoomReducer>;
export type LeaveRoomParams = __Infer<typeof LeaveRoomReducer>;
export type SetInputParams = __Infer<typeof SetInputReducer>;
export type SetNameParams = __Infer<typeof SetNameReducer>;
export type TickParams = __Infer<typeof TickReducer>;
export type UseZombieAbilityParams = __Infer<typeof UseZombieAbilityReducer>;

