// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import SetGameModeReducer from "../set_game_mode_reducer";
import SetInputReducer from "../set_input_reducer";
import SetNameReducer from "../set_name_reducer";
import TickReducer from "../tick_reducer";
import UseZombieAbilityReducer from "../use_zombie_ability_reducer";

export type SetGameModeParams = __Infer<typeof SetGameModeReducer>;
export type SetInputParams = __Infer<typeof SetInputReducer>;
export type SetNameParams = __Infer<typeof SetNameReducer>;
export type TickParams = __Infer<typeof TickReducer>;
export type UseZombieAbilityParams = __Infer<typeof UseZombieAbilityReducer>;

